import type {
  Account,
  Category,
  Channel,
  IntegrationStatus,
  KeywordRule,
  Notification,
  ReconciliationLog,
  Transaction,
  TransactionProof,
  User,
} from "@/lib/types";

export const NOW = "2026-04-01T14:00:00+08:00";

export const users: User[] = [
  {
    id: "usr_owner",
    name: "Raka Setiawan",
    email: "raka@o-reio.internal",
    role: "OWNER",
    title: "Owner / Super Admin",
  },
  {
    id: "usr_ops",
    name: "Ayla Pratama",
    email: "ayla@o-reio.internal",
    role: "OPS_MANAGER",
    title: "Operations Manager",
  },
  {
    id: "usr_finance",
    name: "Nadia Putri",
    email: "nadia@o-reio.internal",
    role: "FINANCE",
    title: "Finance / Admin",
  },
];

export const categories: Category[] = [
  { id: "cat_income_wholesale", name: "Wholesale Income", type: "INCOME" },
  { id: "cat_income_consignment", name: "Consignment Income", type: "INCOME" },
  { id: "cat_income_shopify", name: "Shopify Income", type: "INCOME" },
  { id: "cat_income_tiktok", name: "TikTok Shop Income", type: "INCOME" },
  { id: "cat_income_offline", name: "Offline Store Income", type: "INCOME" },
  { id: "cat_growth_root", name: "Growth", type: "EXPENSE", expenseGroup: "GROWTH" },
  {
    id: "cat_growth_promote_online_ads",
    name: "Promote-Online-ads",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_promote_tiktok_ads",
    name: "Promote-Tiktok-ads",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_promote_tiktok_salary",
    name: "Promote-Tiktok-Salary",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_promote_tiktok_live",
    name: "Promote-Tiktok-live",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_promote_tiktok_commiss",
    name: "Promote-Tiktok-Commiss",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_promote_tiktok_shop_fee",
    name: "Promote-Tiktok-Shop-Fee",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_sosmed_team",
    name: "Sosmed-Team",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  {
    id: "cat_growth_sosmed_shoot",
    name: "Sosmed-Shoot",
    type: "EXPENSE",
    parentId: "cat_growth_root",
  },
  { id: "cat_cost_root", name: "Cost", type: "EXPENSE", expenseGroup: "COST" },
  {
    id: "cat_cost_production_bangkok",
    name: "Production-Bangkok",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_production_brass",
    name: "Production-Brass",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_production_worker",
    name: "Production-Worker",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_production_package",
    name: "Production-Package",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_production_material",
    name: "Production-Material",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_shipping_dhl",
    name: "Shipping-DHL",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_shipping_baraka",
    name: "Shipping-Baraka",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_shipping_grab",
    name: "Shipping-Grab",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  {
    id: "cat_cost_shipping_package",
    name: "Shipping-package",
    type: "EXPENSE",
    parentId: "cat_cost_root",
  },
  { id: "cat_overhead_root", name: "Overhead", type: "EXPENSE", expenseGroup: "OVERHEAD" },
  {
    id: "cat_overhead_office_salaries",
    name: "Office-Salaries",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
  {
    id: "cat_overhead_office_rent",
    name: "Office-Rent",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
  {
    id: "cat_overhead_office_power",
    name: "Office-Power",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
  {
    id: "cat_overhead_office_operational",
    name: "Office-Operational",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
  {
    id: "cat_overhead_office_tax",
    name: "Office-Tax",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
  {
    id: "cat_overhead_office_refund",
    name: "Office-Refund",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
  {
    id: "cat_overhead_german_expense",
    name: "German-Expense",
    type: "EXPENSE",
    parentId: "cat_overhead_root",
  },
];

export const channels: Channel[] = [
  { id: "chn_bca", name: "BCA", type: "BANK", status: "SYNCED", isCashAccount: true },
  { id: "chn_wise", name: "Wise", type: "GATEWAY", status: "MANUAL", isCashAccount: true },
  {
    id: "chn_pingpong",
    name: "Pingpong",
    type: "GATEWAY",
    status: "MANUAL",
    isCashAccount: true,
  },
  {
    id: "chn_aspire",
    name: "Aspire",
    type: "WALLET",
    status: "MANUAL",
    isCashAccount: true,
  },
  {
    id: "chn_shopify",
    name: "Shopify",
    type: "MODULE",
    status: "ATTENTION",
    isCashAccount: false,
  },
  {
    id: "chn_tiktok",
    name: "TikTok Shop",
    type: "MODULE",
    status: "ATTENTION",
    isCashAccount: false,
  },
  {
    id: "chn_offline",
    name: "Offline Store",
    type: "MODULE",
    status: "MANUAL",
    isCashAccount: false,
  },
];

export const accounts: Account[] = [
  {
    id: "bca_pt",
    name: "BCA PT",
    currency: "IDR",
    source: "auto",
    type: "bank",
    group: "local",
  },
  {
    id: "bca_cv",
    name: "BCA CV",
    currency: "IDR",
    source: "manual",
    type: "bank",
    group: "local",
  },
  {
    id: "bca_sgd_cv",
    name: "BCA SGD CV",
    currency: "SGD",
    source: "manual",
    type: "bank",
    group: "local",
  },
  {
    id: "bca_credit_card",
    name: "BCA Credit Card",
    currency: "IDR",
    source: "manual",
    type: "bank",
    group: "local",
  },
  {
    id: "bca_blu",
    name: "BCA Blu",
    currency: "IDR",
    source: "manual",
    type: "bank",
    group: "local",
  },
  {
    id: "wise",
    name: "Wise",
    currency: "USD",
    source: "manual",
    type: "wallet",
    group: "foreign",
  },
  {
    id: "pingpong",
    name: "PingPong",
    currency: "USD",
    source: "manual",
    type: "platform",
    group: "foreign",
  },
  {
    id: "aspire_sgd",
    name: "Aspire SGD",
    currency: "SGD",
    source: "manual",
    type: "wallet",
    group: "foreign",
  },
  {
    id: "aspire_eur",
    name: "Aspire EUR",
    currency: "EUR",
    source: "manual",
    type: "wallet",
    group: "foreign",
  },
  {
    id: "payout_holding",
    name: "Payout Holding",
    currency: "IDR",
    source: "manual",
    type: "holding",
    group: "holding",
  },
  {
    id: "settlement_holding",
    name: "Settlement Holding",
    currency: "IDR",
    source: "manual",
    type: "holding",
    group: "holding",
  },
  {
    id: "tiktok_settlement",
    name: "TikTok Settlement",
    currency: "IDR",
    source: "manual",
    type: "holding",
    group: "holding",
  },
];

const sampleTransactionProof: TransactionProof = {
  name: "shopify-payout-0401.png",
  mimeType: "image/png",
  dataUrl:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADElEQVR42mP8/5+hHgAHggJ/Pk0qWQAAAABJRU5ErkJggg==",
  size: 68,
};

export const transactions: Transaction[] = [
  {
    id: "txn_apr_shopify",
    amount: 5850,
    originalCurrency: "USD",
    exchangeRate: 16100,
    baseAmount: 94185000,
    transactionDate: "2026-04-01T08:12:00+08:00",
    description: "Pingpong Shopify payout batch 04/01",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_shopify",
    channelId: "chn_pingpong",
    proof: sampleTransactionProof,
    loggedBy: "usr_finance",
  },
  {
    id: "txn_apr_wholesale",
    amount: 21450000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 21450000,
    transactionDate: "2026-04-01T09:40:00+08:00",
    description: "Wholesale order settlement from Wise",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "PENDING",
    categoryId: "cat_income_wholesale",
    channelId: "chn_wise",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_apr_tiktok_income",
    amount: 18200000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 18200000,
    transactionDate: "2026-04-01T10:12:00+08:00",
    description: "TikTok Shop settlement",
    kind: "INCOME",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_tiktok",
    channelId: "chn_tiktok",
  },
  {
    id: "txn_apr_fb_ads",
    amount: 22400000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 22400000,
    transactionDate: "2026-04-01T11:00:00+08:00",
    description: "FACEBOOK ads billing cycle",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_growth_promote_online_ads",
    channelId: "chn_bca",
  },
  {
    id: "txn_apr_tiktok_ads",
    amount: 14900000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 14900000,
    transactionDate: "2026-04-01T11:10:00+08:00",
    description: "TikTok ads top up from Aspire",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "PENDING",
    categoryId: "cat_growth_promote_tiktok_ads",
    channelId: "chn_aspire",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_apr_salary",
    amount: 17500000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 17500000,
    transactionDate: "2026-04-01T11:30:00+08:00",
    description: "Salary payout March cycle",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_salaries",
    channelId: "chn_bca",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_apr_inventory",
    amount: 18600000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 18600000,
    transactionDate: "2026-04-01T12:20:00+08:00",
    description: "Inventory procurement warehouse batch",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_cost_production_material",
    channelId: "chn_bca",
  },
  {
    id: "txn_apr_rent",
    amount: 7900000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 7900000,
    transactionDate: "2026-04-01T13:00:00+08:00",
    description: "HQ rent transfer",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_rent",
    channelId: "chn_bca",
  },
  {
    id: "txn_apr_grab",
    amount: 2600000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 2600000,
    transactionDate: "2026-04-01T13:12:00+08:00",
    description: "OVO top up for Grab shipping",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_cost_shipping_grab",
    channelId: "chn_bca",
  },
  {
    id: "txn_apr_software",
    amount: 1450000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 1450000,
    transactionDate: "2026-04-01T13:22:00+08:00",
    description: "Monthly software stack licenses",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_operational",
    channelId: "chn_aspire",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_mar_shopify",
    amount: 5500,
    originalCurrency: "USD",
    exchangeRate: 16050,
    baseAmount: 88275000,
    transactionDate: "2026-03-20T10:00:00+08:00",
    description: "Pingpong Shopify payout batch 03/20",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_shopify",
    channelId: "chn_pingpong",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_mar_wholesale",
    amount: 28500000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 28500000,
    transactionDate: "2026-03-18T10:15:00+08:00",
    description: "Wholesale invoice closing",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_wholesale",
    channelId: "chn_wise",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_mar_offline",
    amount: 12300000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 12300000,
    transactionDate: "2026-03-22T17:45:00+08:00",
    description: "Offline store weekly closing",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_offline",
    channelId: "chn_offline",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_mar_fb_ads",
    amount: 16200000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 16200000,
    transactionDate: "2026-03-16T11:00:00+08:00",
    description: "FACEBOOK ads billing cycle",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_growth_promote_online_ads",
    channelId: "chn_bca",
  },
  {
    id: "txn_mar_salary",
    amount: 17800000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 17800000,
    transactionDate: "2026-03-25T08:00:00+08:00",
    description: "Salary payout February cycle",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_salaries",
    channelId: "chn_bca",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_mar_inventory",
    amount: 13600000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 13600000,
    transactionDate: "2026-03-14T15:15:00+08:00",
    description: "Inventory restock for wholesale launch",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_cost_production_material",
    channelId: "chn_bca",
  },
  {
    id: "txn_mar_rent",
    amount: 8200000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 8200000,
    transactionDate: "2026-03-01T09:00:00+08:00",
    description: "HQ rent transfer",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_rent",
    channelId: "chn_bca",
  },
  {
    id: "txn_mar_software",
    amount: 2500000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 2500000,
    transactionDate: "2026-03-27T12:00:00+08:00",
    description: "Software renewals and reporting tools",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_operational",
    channelId: "chn_aspire",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_feb_shopify",
    amount: 5100,
    originalCurrency: "USD",
    exchangeRate: 15980,
    baseAmount: 81498000,
    transactionDate: "2026-02-18T10:10:00+08:00",
    description: "Pingpong Shopify payout batch 02/18",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_shopify",
    channelId: "chn_pingpong",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_feb_consignment",
    amount: 16900000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 16900000,
    transactionDate: "2026-02-12T16:30:00+08:00",
    description: "Consignment payout from partner stores",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_consignment",
    channelId: "chn_wise",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_feb_growth",
    amount: 14800000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 14800000,
    transactionDate: "2026-02-10T11:00:00+08:00",
    description: "FACEBOOK and TikTok blended ads billing",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_growth_promote_online_ads",
    channelId: "chn_bca",
  },
  {
    id: "txn_feb_cost",
    amount: 27600000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 27600000,
    transactionDate: "2026-02-24T08:20:00+08:00",
    description: "Salary and operations cost bundle",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_cost_production_worker",
    channelId: "chn_bca",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_feb_overhead",
    amount: 9200000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 9200000,
    transactionDate: "2026-02-28T13:00:00+08:00",
    description: "Rent, shipping, and software blend",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_operational",
    channelId: "chn_bca",
  },
  {
    id: "txn_jan_shopify",
    amount: 4820,
    originalCurrency: "USD",
    exchangeRate: 15820,
    baseAmount: 76252400,
    transactionDate: "2026-01-18T09:15:00+08:00",
    description: "Pingpong Shopify payout batch 01/18",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_shopify",
    channelId: "chn_pingpong",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_jan_wholesale",
    amount: 21500000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 21500000,
    transactionDate: "2026-01-22T10:00:00+08:00",
    description: "Wholesale collections",
    kind: "INCOME",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_income_wholesale",
    channelId: "chn_wise",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_jan_growth",
    amount: 11900000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 11900000,
    transactionDate: "2026-01-10T11:00:00+08:00",
    description: "FACEBOOK ads billing cycle",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_growth_promote_online_ads",
    channelId: "chn_bca",
  },
  {
    id: "txn_jan_cost",
    amount: 25800000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 25800000,
    transactionDate: "2026-01-24T08:00:00+08:00",
    description: "Salary and inventory restock",
    kind: "EXPENSE",
    entryType: "MANUAL",
    verificationStatus: "VERIFIED",
    categoryId: "cat_cost_production_worker",
    channelId: "chn_bca",
    loggedBy: "usr_finance",
  },
  {
    id: "txn_jan_overhead",
    amount: 8400000,
    originalCurrency: "IDR",
    exchangeRate: 1,
    baseAmount: 8400000,
    transactionDate: "2026-01-02T09:00:00+08:00",
    description: "Rent and software commitments",
    kind: "EXPENSE",
    entryType: "AUTO",
    verificationStatus: "VERIFIED",
    categoryId: "cat_overhead_office_operational",
    channelId: "chn_bca",
  },
];

export const keywordRules: KeywordRule[] = [
  {
    id: "rule_facebook",
    keyword: "FACEBOOK",
    categoryId: "cat_growth_promote_online_ads",
    note: "Growth spend billed through Meta.",
    createdBy: "usr_owner",
    updatedAt: NOW,
  },
  {
    id: "rule_ovo",
    keyword: "OVO",
    categoryId: "cat_cost_shipping_grab",
    note: "Map wallet top-ups to Grab shipping cost.",
    createdBy: "usr_owner",
    updatedAt: NOW,
  },
  {
    id: "rule_salary",
    keyword: "SALARY",
    categoryId: "cat_overhead_office_salaries",
    note: "Office salaries belong in overhead.",
    createdBy: "usr_owner",
    updatedAt: NOW,
  },
];

export const reconciliationLogs: ReconciliationLog[] = [
  {
    id: "rec_0401",
    checkTime: "2026-04-01T13:45:00+08:00",
    status: "DISCREPANCY",
    details: "Two manual entries are still pending verification before the April board view is complete.",
    expectedTotal: 179835000,
    actualTotal: 164935000,
  },
  {
    id: "rec_0331",
    checkTime: "2026-03-31T17:20:00+08:00",
    status: "COMPLETE",
    details: "BCA hourly sync matched the March closing ledger.",
    expectedTotal: 115975000,
    actualTotal: 115975000,
  },
  {
    id: "rec_0331_am",
    checkTime: "2026-03-31T09:00:00+08:00",
    status: "COMPLETE",
    details: "Morning sync posted cleanly with no unmatched transactions.",
    expectedTotal: 45600000,
    actualTotal: 45600000,
  },
];

export const notifications: Notification[] = [
  {
    id: "notif_sync",
    title: "Hourly BCA sync succeeded",
    message: "The latest automated bank pull completed at 13:45 with 28 statements normalized.",
    severity: "INFO",
    createdAt: NOW,
    channel: "IN_APP",
  },
  {
    id: "notif_modules",
    title: "Module bridge needs review",
    message: "The Shopify and wholesale bridges are marked ready for frontend mapping, but backend sync is still stubbed.",
    severity: "WARNING",
    createdAt: "2026-04-01T12:40:00+08:00",
    channel: "IN_APP",
  },
];

export const integrations: IntegrationStatus[] = [
  {
    id: "int_bca",
    name: "BCA API",
    surface: "API",
    state: "SYNCED",
    lastEvent: "2026-04-01T13:45:00+08:00",
    note: "Hourly sync healthy. Last fetch normalized and categorized 28 bank movements.",
  },
  {
    id: "int_whatsapp",
    name: "WhatsApp Alerting",
    surface: "ALERT",
    state: "ATTENTION",
    lastEvent: "2026-04-01T14:00:00+08:00",
    note: "Red-state alert template is ready in the UI, pending live API credentials.",
  },
  {
    id: "int_signia",
    name: "o-signia",
    surface: "MODULE",
    state: "SYNCED",
    lastEvent: "2026-04-01T11:30:00+08:00",
    note: "Report payload schema mapped. Frontend can consume status and summary cards.",
  },
  {
    id: "int_wholesale",
    name: "wholesale",
    surface: "MODULE",
    state: "ATTENTION",
    lastEvent: "2026-04-01T11:20:00+08:00",
    note: "Orders are available as mocked contract data; reconciliation waits on backend handoff.",
  },
  {
    id: "int_pingpong",
    name: "Pingpong",
    surface: "GATEWAY",
    state: "MANUAL",
    lastEvent: "2026-04-01T08:12:00+08:00",
    note: "Manual foreign-currency intake remains active in V1 with operator-entered rates.",
  },
  {
    id: "int_wise",
    name: "Wise",
    surface: "GATEWAY",
    state: "MANUAL",
    lastEvent: "2026-04-01T09:40:00+08:00",
    note: "Manual settlement input is enabled for wholesale and consignment receipts.",
  },
  {
    id: "int_aspire",
    name: "Aspire",
    surface: "GATEWAY",
    state: "MANUAL",
    lastEvent: "2026-04-01T11:10:00+08:00",
    note: "Wallet expense logging is available with manual FX conversion and verification tracking.",
  },
];
